backend:
  name: git-gateway
  branch: main   # or 'master' if your repo uses that

media_folder: "uploads"        # folder for uploaded images
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: ""
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }
